services:
  - type: web
    name: budget-deploy2
    runtime: node
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install && NODE_OPTIONS=--use-system-ca npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: APPLE_CLIENT_ID
        sync: false
      - key: ADMIN_EMAIL
        sync: false
